app:
  port: 8090
  loglevel: debug
newrelic:
  license: qwerty12345678asdfghqwerty12345678asdfgh
  app.name: gl
  enabled: false
statsd:
  host: localhost:8125
  prefix: gi
placeholder:
  host: http://localhost:8090